# Generated by Django 4.1.7 on 2023-07-24 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patientID", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                ("age", models.CharField(max_length=3)),
                ("birthday", models.DateField()),
                ("contact", models.CharField(max_length=20)),
                (
                    "diagnosis",
                    models.CharField(
                        choices=[
                            ("C00 - Neoplasia Lábio", "C00 - Neoplasia Lábio"),
                            (
                                "C01 - Neoplasia Base de Língua",
                                "C01 - Neoplasia Base de Língua",
                            ),
                            (
                                "C02 - Neoplasia Outras partes e partes não especificadas da língua",
                                "C02 - Neoplasia Outras partes e partes não especificadas da língua",
                            ),
                            ("C03 - Neoplasia Gengiva", "C03 - Neoplasia Gengiva"),
                            (
                                "C04 - Neoplasia Assoalho da boca",
                                "C04 - Neoplasia Assoalho da boca",
                            ),
                            ("C05 - Neoplasia Palato", "C05 - Neoplasia Palato"),
                            (
                                "C06 - Neoplasia Outras partes e partes não especificadas da boca",
                                "C06 - Neoplasia Outras partes e partes não especificadas da boca",
                            ),
                            (
                                "C07 - Neoplasia Glândula parótida",
                                "C07 - Neoplasia Glândula parótida",
                            ),
                            (
                                "C08 - Neoplasia Outras glândulas salivares maiores e glândulas salivares maiores não específicadas",
                                "C08 - Neoplasia Outras glândulas salivares maiores e glândulas salivares maiores não específicadas",
                            ),
                            ("C09 - Neoplasia Amígdala", "C09 - Neoplasia Amígdala"),
                            (
                                "C10 - Neoplasia Orofaringe",
                                "C10 - Neoplasia Orofaringe",
                            ),
                            (
                                "C11 - Neoplasia Nasofaringe",
                                "C11 - Neoplasia Nasofaringe",
                            ),
                            (
                                "C12 - Neoplasia Seio piriforme",
                                "C12 - Neoplasia Seio piriforme",
                            ),
                            (
                                "C13 - Neoplasia Hipofaringe",
                                "C13 - Neoplasia Hipofaringe",
                            ),
                            (
                                "C14 - Neoplasia Outras localizações e localizações mal definidas do lábio, cavidade oral e faringe",
                                "C14 - Neoplasia Outras localizações e localizações mal definidas do lábio, cavidade oral e faringe",
                            ),
                            ("C15 - Neoplasia Esófago", "C15 - Neoplasia Esófago"),
                            ("C16 - Neoplasia Estômago", "C16 - Neoplasia Estômago"),
                            (
                                "C17 - Neoplasia Intestino delgado",
                                "C17 - Neoplasia Intestino delgado",
                            ),
                            ("C18 - Neoplasia Cólon", "C18 - Neoplasia Cólon"),
                            (
                                "C19 - Neoplasia Junção retossigmóide",
                                "C19 - Neoplasia Junção retossigmóide",
                            ),
                            ("C20 - Neoplasia Reto", "C20 - Neoplasia Reto"),
                            (
                                "C21 - Neoplasia Anal e canal anal",
                                "C21 - Neoplasia Anal e canal anal",
                            ),
                            (
                                "C22 - Neoplasia Fígado e vias biliares intrahepáticas",
                                "C22 - Neoplasia Fígado e vias biliares intrahepáticas",
                            ),
                            (
                                "C23 - Neoplasia Vesícula biliar",
                                "C23 - Neoplasia Vesícula biliar",
                            ),
                            (
                                "C24 - Neoplasia Outras partes e partes não especificadas das vias biliares",
                                "C24 - Neoplasia Outras partes e partes não especificadas das vias biliares",
                            ),
                            ("C25 - Neoplasia Pâncreas", "C25 - Neoplasia Pâncreas"),
                            (
                                "C26 - Neoplasia Outros órgãos digestivos e localizações mal definidas do aparelho digestivo",
                                "C26 - Neoplasia Outros órgãos digestivos e localizações mal definidas do aparelho digestivo",
                            ),
                            ("C27 - Neoplasia ", "C27 - Neoplasia "),
                            ("C28 - Neoplasia ", "C28 - Neoplasia "),
                            ("C29 - Neoplasia ", "C29 - Neoplasia "),
                            (
                                "C30 - Neoplasia Cavidade nasal e ouvido médio",
                                "C30 - Neoplasia Cavidade nasal e ouvido médio",
                            ),
                            (
                                "C31 - Neoplasia Seios da face",
                                "C31 - Neoplasia Seios da face",
                            ),
                            ("C32 - Neoplasia Laringe", "C32 - Neoplasia Laringe"),
                            ("C33 - Neoplasia Traquéia", "C33 - Neoplasia Traquéia"),
                            (
                                "C34 - Neoplasia Brônquios e pulmões",
                                "C34 - Neoplasia Brônquios e pulmões",
                            ),
                            ("C35 - Neoplasia ", "C35 - Neoplasia "),
                            ("C36 - Neoplasia ", "C36 - Neoplasia "),
                            ("C37 - Neoplasia Timo", "C37 - Neoplasia Timo"),
                            (
                                "C38 - Neoplasia Coração, mediastino e pleura",
                                "C38 - Neoplasia Coração, mediastino e pleura",
                            ),
                            (
                                "C39 - Neoplasia Outras localizações e localizações mal definifas do aparelho respiratório e dos órgãos intratorácicos",
                                "C39 - Neoplasia Outras localizações e localizações mal definifas do aparelho respiratório e dos órgãos intratorácicos",
                            ),
                            (
                                "C40 - Neoplasia Ossos, articulações e cartilagens articulares dos membros",
                                "C40 - Neoplasia Ossos, articulações e cartilagens articulares dos membros",
                            ),
                            (
                                "C41 - Neoplasia Ossos, articulações e cartilagens articulares de outras localizações e de localizações não especificadas",
                                "C41 - Neoplasia Ossos, articulações e cartilagens articulares de outras localizações e de localizações não especificadas",
                            ),
                            (
                                "C42 - Neoplasia Sistemas hematopoiético e reticuloendotelial",
                                "C42 - Neoplasia Sistemas hematopoiético e reticuloendotelial",
                            ),
                            ("C43 - Neoplasia ", "C43 - Neoplasia "),
                            ("C44 - Neoplasia Pele", "C44 - Neoplasia Pele"),
                            ("C45 - Neoplasia ", "C45 - Neoplasia "),
                            ("C46 - Neoplasia ", "C46 - Neoplasia "),
                            (
                                "C47 - Neoplasia Nervos periféricos e sistema nervoso autónomo",
                                "C47 - Neoplasia Nervos periféricos e sistema nervoso autónomo",
                            ),
                            (
                                "C48 - Neoplasia Retroperitónio e peritónio",
                                "C48 - Neoplasia Retroperitónio e peritónio",
                            ),
                            (
                                "C49 - Neoplasia Tecido conjuntivo, subcutâneo e outros tecidos moles",
                                "C49 - Neoplasia Tecido conjuntivo, subcutâneo e outros tecidos moles",
                            ),
                            ("C50 - Neoplasia Mama", "C50 - Neoplasia Mama"),
                            ("C51 - Neoplasia Vulva", "C51 - Neoplasia Vulva"),
                            ("C52 - Neoplasia Vagina", "C52 - Neoplasia Vagina"),
                            (
                                "C53 - Neoplasia Colo do útero",
                                "C53 - Neoplasia Colo do útero",
                            ),
                            (
                                "C54 - Neoplasia Corpo do útero",
                                "C54 - Neoplasia Corpo do útero",
                            ),
                            (
                                "C55 - Neoplasia Útero, soe",
                                "C55 - Neoplasia Útero, soe",
                            ),
                            ("C56 - Neoplasia Ovário", "C56 - Neoplasia Ovário"),
                            (
                                "C57 - Neoplasia Outros órgãos genitais femininos e não específicados",
                                "C57 - Neoplasia Outros órgãos genitais femininos e não específicados",
                            ),
                            ("C58 - Neoplasia Placenta", "C58 - Neoplasia Placenta"),
                            ("C59 - Neoplasia Pénis", "C59 - Neoplasia Pénis"),
                            ("C60 - Neoplasia Próstata", "C60 - Neoplasia Próstata"),
                            ("C61 - Neoplasia Próstata", "C61 - Neoplasia Próstata"),
                            ("C62 - Neoplasia Testículo", "C62 - Neoplasia Testículo"),
                            (
                                "C63 - Neoplasia Outros órgãos genitais masculinos e não especificados",
                                "C63 - Neoplasia Outros órgãos genitais masculinos e não especificados",
                            ),
                            ("C64 - Neoplasia Rim", "C64 - Neoplasia Rim"),
                            (
                                "C65 - Neoplasia Pelve renal",
                                "C65 - Neoplasia Pelve renal",
                            ),
                            ("C66 - Neoplasia Ureter", "C66 - Neoplasia Ureter"),
                            ("C67 - Neoplasia Bexiga", "C67 - Neoplasia Bexiga"),
                            (
                                "C68 - Neoplasia Outros órgãos urinários e não específicados",
                                "C68 - Neoplasia Outros órgãos urinários e não específicados",
                            ),
                            (
                                "C69 - Neoplasia Olho e anexos",
                                "C69 - Neoplasia Olho e anexos",
                            ),
                            ("C70 - Neoplasia Meninges", "C70 - Neoplasia Meninges"),
                            ("C71 - Neoplasia Encéfalo", "C71 - Neoplasia Encéfalo"),
                            (
                                "C72 - Neoplasia Medula espinhal, nervos cranianos e outras partes do sistema nervoso central",
                                "C72 - Neoplasia Medula espinhal, nervos cranianos e outras partes do sistema nervoso central",
                            ),
                            (
                                "C73 - Neoplasia Glândula tireóide",
                                "C73 - Neoplasia Glândula tireóide",
                            ),
                            (
                                "C74 - Neoplasia Glândula supra-renal",
                                "C74 - Neoplasia Glândula supra-renal",
                            ),
                            (
                                "C75 - Neoplasia Outras glândulas endócrinas e estruturas relacionadas",
                                "C75 - Neoplasia Outras glândulas endócrinas e estruturas relacionadas",
                            ),
                            ("C76 - Neoplasia ", "C76 - Neoplasia "),
                            (
                                "C77 - Neoplasia Linfonodos",
                                "C77 - Neoplasia Linfonodos",
                            ),
                            ("C78 - Neoplasia ", "C78 - Neoplasia "),
                            ("C79 - Neoplasia ", "C79 - Neoplasia "),
                        ],
                        max_length=200,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Suitability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating_1",
                    models.CharField(
                        choices=[
                            ("Completely Disagree", "Completely Disagree"),
                            ("Disagree", "Disagree"),
                            ("Neutral", "Neutral"),
                            ("Agree", "Agree"),
                            ("Completely Agree", "Completely Agree"),
                        ],
                        default="Neutral",
                        max_length=20,
                    ),
                ),
                (
                    "rating_2",
                    models.CharField(
                        choices=[
                            ("Completely Disagree", "Completely Disagree"),
                            ("Disagree", "Disagree"),
                            ("Neutral", "Neutral"),
                            ("Agree", "Agree"),
                            ("Completely Agree", "Completely Agree"),
                        ],
                        default="Neutral",
                        max_length=20,
                    ),
                ),
                (
                    "rating_3",
                    models.CharField(
                        choices=[
                            ("Completely Disagree", "Completely Disagree"),
                            ("Disagree", "Disagree"),
                            ("Neutral", "Neutral"),
                            ("Agree", "Agree"),
                            ("Completely Agree", "Completely Agree"),
                        ],
                        default="Neutral",
                        max_length=20,
                    ),
                ),
                (
                    "rating_4",
                    models.CharField(
                        choices=[
                            ("Completely Disagree", "Completely Disagree"),
                            ("Disagree", "Disagree"),
                            ("Neutral", "Neutral"),
                            ("Agree", "Agree"),
                            ("Completely Agree", "Completely Agree"),
                        ],
                        default="Neutral",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Symptom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symptomID", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Treatment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=40)),
                ("name", models.CharField(max_length=40)),
                ("symptoms", models.ManyToManyField(to="guideline.symptom")),
            ],
        ),
        migrations.CreateModel(
            name="Occurrence",
            fields=[
                ("occurrenceID", models.AutoField(primary_key=True, serialize=False)),
                ("date_time", models.DateTimeField()),
                ("comments", models.TextField()),
                (
                    "choosenTreatments",
                    models.ManyToManyField(blank=True, to="guideline.treatment"),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="guideline.patient",
                    ),
                ),
                (
                    "suitability",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="guideline.suitability",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NurseUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="custom_user_set",
                        related_query_name="custom_user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="custom_user_set",
                        related_query_name="custom_user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MSAS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("validation", models.BooleanField(default=False)),
                ("frequency", models.IntegerField(default=0)),
                ("severity", models.IntegerField(default=0)),
                ("discomfort", models.IntegerField(default=0)),
                (
                    "occurrence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="guideline.occurrence",
                    ),
                ),
                (
                    "symptom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="guideline.symptom",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                ("feedbackID", models.AutoField(primary_key=True, serialize=False)),
                ("validation", models.BooleanField(default=False)),
                ("frequency", models.IntegerField()),
                ("severity", models.IntegerField()),
                ("discomfort", models.IntegerField()),
                (
                    "occurrence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="guideline.occurrence",
                    ),
                ),
                (
                    "symptom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="guideline.symptom",
                    ),
                ),
            ],
        ),
    ]
