# Generated by Django 4.1.7 on 2023-08-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guideline", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="diagnosis",
            field=models.CharField(
                choices=[
                    ("C00 - Neoplasia Lábio", "C00 - Neoplasia Lábio"),
                    (
                        "C01 - Neoplasia Base de Língua",
                        "C01 - Neoplasia Base de Língua",
                    ),
                    (
                        "C02 - Neoplasia Outras partes e partes não especificadas da língua",
                        "C02 - Neoplasia Outras partes e partes não especificadas da língua",
                    ),
                    ("C03 - Neoplasia Gengiva", "C03 - Neoplasia Gengiva"),
                    (
                        "C04 - Neoplasia Assoalho da boca",
                        "C04 - Neoplasia Assoalho da boca",
                    ),
                    ("C05 - Neoplasia Palato", "C05 - Neoplasia Palato"),
                    (
                        "C06 - Neoplasia Outras partes e partes não especificadas da boca",
                        "C06 - Neoplasia Outras partes e partes não especificadas da boca",
                    ),
                    (
                        "C07 - Neoplasia Glândula parótida",
                        "C07 - Neoplasia Glândula parótida",
                    ),
                    (
                        "C08 - Neoplasia Outras glândulas salivares maiores e glândulas salivares maiores não específicadas",
                        "C08 - Neoplasia Outras glândulas salivares maiores e glândulas salivares maiores não específicadas",
                    ),
                    ("C09 - Neoplasia Amígdala", "C09 - Neoplasia Amígdala"),
                    ("C10 - Neoplasia Orofaringe", "C10 - Neoplasia Orofaringe"),
                    ("C11 - Neoplasia Nasofaringe", "C11 - Neoplasia Nasofaringe"),
                    (
                        "C12 - Neoplasia Seio piriforme",
                        "C12 - Neoplasia Seio piriforme",
                    ),
                    ("C13 - Neoplasia Hipofaringe", "C13 - Neoplasia Hipofaringe"),
                    (
                        "C14 - Neoplasia Outras localizações e localizações mal definidas do lábio, cavidade oral e faringe",
                        "C14 - Neoplasia Outras localizações e localizações mal definidas do lábio, cavidade oral e faringe",
                    ),
                    ("C15 - Neoplasia Esófago", "C15 - Neoplasia Esófago"),
                    ("C16 - Neoplasia Estômago", "C16 - Neoplasia Estômago"),
                    (
                        "C17 - Neoplasia Intestino delgado",
                        "C17 - Neoplasia Intestino delgado",
                    ),
                    ("C18 - Neoplasia Cólon", "C18 - Neoplasia Cólon"),
                    (
                        "C19 - Neoplasia Junção retossigmóide",
                        "C19 - Neoplasia Junção retossigmóide",
                    ),
                    ("C20 - Neoplasia Reto", "C20 - Neoplasia Reto"),
                    (
                        "C21 - Neoplasia Anal e canal anal",
                        "C21 - Neoplasia Anal e canal anal",
                    ),
                    (
                        "C22 - Neoplasia Fígado e vias biliares intrahepáticas",
                        "C22 - Neoplasia Fígado e vias biliares intrahepáticas",
                    ),
                    (
                        "C23 - Neoplasia Vesícula biliar",
                        "C23 - Neoplasia Vesícula biliar",
                    ),
                    (
                        "C24 - Neoplasia Outras partes e partes não especificadas das vias biliares",
                        "C24 - Neoplasia Outras partes e partes não especificadas das vias biliares",
                    ),
                    ("C25 - Neoplasia Pâncreas", "C25 - Neoplasia Pâncreas"),
                    (
                        "C26 - Neoplasia Outros órgãos digestivos e localizações mal definidas do aparelho digestivo",
                        "C26 - Neoplasia Outros órgãos digestivos e localizações mal definidas do aparelho digestivo",
                    ),
                    (
                        "C30 - Neoplasia Cavidade nasal e ouvido médio",
                        "C30 - Neoplasia Cavidade nasal e ouvido médio",
                    ),
                    ("C31 - Neoplasia Seios da face", "C31 - Neoplasia Seios da face"),
                    ("C32 - Neoplasia Laringe", "C32 - Neoplasia Laringe"),
                    ("C33 - Neoplasia Traquéia", "C33 - Neoplasia Traquéia"),
                    (
                        "C34 - Neoplasia Brônquios e pulmões",
                        "C34 - Neoplasia Brônquios e pulmões",
                    ),
                    ("C37 - Neoplasia Timo", "C37 - Neoplasia Timo"),
                    (
                        "C38 - Neoplasia Coração, mediastino e pleura",
                        "C38 - Neoplasia Coração, mediastino e pleura",
                    ),
                    (
                        "C39 - Neoplasia Outras localizações e localizações mal definifas do aparelho respiratório e dos órgãos intratorácicos",
                        "C39 - Neoplasia Outras localizações e localizações mal definifas do aparelho respiratório e dos órgãos intratorácicos",
                    ),
                    (
                        "C40 - Neoplasia Ossos, articulações e cartilagens articulares dos membros",
                        "C40 - Neoplasia Ossos, articulações e cartilagens articulares dos membros",
                    ),
                    (
                        "C41 - Neoplasia Ossos, articulações e cartilagens articulares de outras localizações e de localizações não especificadas",
                        "C41 - Neoplasia Ossos, articulações e cartilagens articulares de outras localizações e de localizações não especificadas",
                    ),
                    (
                        "C42 - Neoplasia Sistemas hematopoiético e reticuloendotelial",
                        "C42 - Neoplasia Sistemas hematopoiético e reticuloendotelial",
                    ),
                    ("C44 - Neoplasia Pele", "C44 - Neoplasia Pele"),
                    (
                        "C47 - Neoplasia Nervos periféricos e sistema nervoso autónomo",
                        "C47 - Neoplasia Nervos periféricos e sistema nervoso autónomo",
                    ),
                    (
                        "C48 - Neoplasia Retroperitónio e peritónio",
                        "C48 - Neoplasia Retroperitónio e peritónio",
                    ),
                    (
                        "C49 - Neoplasia Tecido conjuntivo, subcutâneo e outros tecidos moles",
                        "C49 - Neoplasia Tecido conjuntivo, subcutâneo e outros tecidos moles",
                    ),
                    ("C50 - Neoplasia Mama", "C50 - Neoplasia Mama"),
                    ("C51 - Neoplasia Vulva", "C51 - Neoplasia Vulva"),
                    ("C52 - Neoplasia Vagina", "C52 - Neoplasia Vagina"),
                    ("C53 - Neoplasia Colo do útero", "C53 - Neoplasia Colo do útero"),
                    (
                        "C54 - Neoplasia Corpo do útero",
                        "C54 - Neoplasia Corpo do útero",
                    ),
                    ("C55 - Neoplasia Útero, soe", "C55 - Neoplasia Útero, soe"),
                    ("C56 - Neoplasia Ovário", "C56 - Neoplasia Ovário"),
                    (
                        "C57 - Neoplasia Outros órgãos genitais femininos e não específicados",
                        "C57 - Neoplasia Outros órgãos genitais femininos e não específicados",
                    ),
                    ("C58 - Neoplasia Placenta", "C58 - Neoplasia Placenta"),
                    ("C59 - Neoplasia Pénis", "C59 - Neoplasia Pénis"),
                    ("C60 - Neoplasia Próstata", "C60 - Neoplasia Próstata"),
                    ("C61 - Neoplasia Próstata", "C61 - Neoplasia Próstata"),
                    ("C62 - Neoplasia Testículo", "C62 - Neoplasia Testículo"),
                    (
                        "C63 - Neoplasia Outros órgãos genitais masculinos e não especificados",
                        "C63 - Neoplasia Outros órgãos genitais masculinos e não especificados",
                    ),
                    ("C64 - Neoplasia Rim", "C64 - Neoplasia Rim"),
                    ("C65 - Neoplasia Pelve renal", "C65 - Neoplasia Pelve renal"),
                    ("C66 - Neoplasia Ureter", "C66 - Neoplasia Ureter"),
                    ("C67 - Neoplasia Bexiga", "C67 - Neoplasia Bexiga"),
                    (
                        "C68 - Neoplasia Outros órgãos urinários e não específicados",
                        "C68 - Neoplasia Outros órgãos urinários e não específicados",
                    ),
                    ("C69 - Neoplasia Olho e anexos", "C69 - Neoplasia Olho e anexos"),
                    ("C70 - Neoplasia Meninges", "C70 - Neoplasia Meninges"),
                    ("C71 - Neoplasia Encéfalo", "C71 - Neoplasia Encéfalo"),
                    (
                        "C72 - Neoplasia Medula espinhal, nervos cranianos e outras partes do sistema nervoso central",
                        "C72 - Neoplasia Medula espinhal, nervos cranianos e outras partes do sistema nervoso central",
                    ),
                    (
                        "C73 - Neoplasia Glândula tireóide",
                        "C73 - Neoplasia Glândula tireóide",
                    ),
                    (
                        "C74 - Neoplasia Glândula supra-renal",
                        "C74 - Neoplasia Glândula supra-renal",
                    ),
                    (
                        "C75 - Neoplasia Outras glândulas endócrinas e estruturas relacionadas",
                        "C75 - Neoplasia Outras glândulas endócrinas e estruturas relacionadas",
                    ),
                    ("C77 - Neoplasia Linfonodos", "C77 - Neoplasia Linfonodos"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="suitability",
            name="rating_1",
            field=models.CharField(
                choices=[
                    ("Discordo completamente", "Discordo completamente"),
                    ("Discordo", "Discordo"),
                    ("Neutro", "Neutro"),
                    ("Concordo", "Concordo"),
                    ("Concordo completamente", "Concordo completamente"),
                ],
                default="Neutral",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="suitability",
            name="rating_2",
            field=models.CharField(
                choices=[
                    ("Discordo completamente", "Discordo completamente"),
                    ("Discordo", "Discordo"),
                    ("Neutro", "Neutro"),
                    ("Concordo", "Concordo"),
                    ("Concordo completamente", "Concordo completamente"),
                ],
                default="Neutral",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="suitability",
            name="rating_3",
            field=models.CharField(
                choices=[
                    ("Discordo completamente", "Discordo completamente"),
                    ("Discordo", "Discordo"),
                    ("Neutro", "Neutro"),
                    ("Concordo", "Concordo"),
                    ("Concordo completamente", "Concordo completamente"),
                ],
                default="Neutral",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="suitability",
            name="rating_4",
            field=models.CharField(
                choices=[
                    ("Discordo completamente", "Discordo completamente"),
                    ("Discordo", "Discordo"),
                    ("Neutro", "Neutro"),
                    ("Concordo", "Concordo"),
                    ("Concordo completamente", "Concordo completamente"),
                ],
                default="Neutral",
                max_length=50,
            ),
        ),
    ]
