# Generated by Django 4.1.7 on 2023-08-25 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "guideline",
            "0002_alter_patient_diagnosis_alter_suitability_rating_1_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="NurseUser",
        ),
    ]
